title: Sanghyeok Jeong's Gallery
author: Sanghyeok Jeong
email: nacl31566@gmail.com
description: >-
  Geography Education, Korea University (2021-)

social:
  instagram: hk._.jng
  github: 1jsh

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
